[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000,immutable"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000,immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000,immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000,immutable"

[[headers]]
  for = "/*"
  [headers.values]
    # We don't use iframes. Block them.
    X-Frame-Options = "DENY"
    # Don't allow Mime-sniffing.
    X-Content-Type-Options = "nosniff"
    # Add reflective XSS protection.
    X-XSS-Protection = "1; mode=block"
    # Force HTTPS only.
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    # Load scripts only via HTTPS and from allowed domains.
    Content-Security-Policy = "default-src https:; script-src https: 'self' 'nonce-93HDK8392dfjh4Gb' 'unsafe-eval' 'sha256-3qFt4qPvMCWVUpjUxP5X57GBKae6RHYZ0rMjn9WuNF4='; style-src https: 'self' 'sha256-ouaL9aaaKO9mYd9/M+uyzYAL1CrOXJVRjV2nFgbGI2E='; object-src 'self'"
    # Only send referred when HTTPS is used.
    Referrer-Policy = "strict-origin-when-cross-origin"

[[plugins]]
package = "netlify-plugin-checklinks"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[plugins]]
package = "netlify-plugin-subfont"
